@startuml Facturacion de una Reserva

Cliente -> Garage:reservar(evento: Evento, garage: Garage)

Garage -> Vehiculo:vehiculo verifica si puede ser reservado
Vehiculo -> Estado : verifica si el estado es disponible
Estado -> disponible : si esta disponible se reserva el vehiculo
Estado -> enReserva: el vehiculo esta reservado
Estado -> enReserva: EL auto en caso de estar reservado llamara a su estado reserva
Estado -> Error:Estado devolvera un error
Estado -> enMantenimiento:el auto en caso de estar en mantenimiento llamara a su estado en manteniumiento
Estado -> Error:Esatdo devolvera un error
Garage -> Vehiculo : garage llama a vehiculo para mandarlo a mantenimiento
Vehiculo -> Estado :vehiculo analiza su estado
Estado -> enMantenimiento: el vehiculo pasa a estar en mantenimiento





@enduml