@startuml

abstract class Vehiculo {
    - abstract matricula: string
    - enMantenimiento: boolean
    - enReserva: boolean
    - necesitaLimpieza: boolean

    + setters_y_getters()
}

class CalculadoraDeTarifas {
    + calcularTarifa(reserva: Reserva, kilometros: number)
}

class Reserva {
    - cant_dias: number
    - vehiculo: Vehiculo
    + crearReserva(fecha_inicio: number, fecha_fin: number, vehiculo: Vehiculo)
}

class Mantenimiento {
    + realizarMantenimiento(vehiculo: Vehiculo)
}

abstract class TipodeVehiculo {
    + abstract obtenerValor()
}

class Compacto {

}
class Sedán {

}
class SUV {

}

' Relaciones

Vehiculo *-l- CalculadoraDeTarifas
Vehiculo *-d- Mantenimiento
Vehiculo *-r- Reserva
Vehiculo <|-d- TipodeVehiculo


TipodeVehiculo <|-- Compacto
TipodeVehiculo <|-- Sedán
TipodeVehiculo <|-- SUV

' Notas

note right of TipodeVehiculo::obtenerValor
    'devuelve un valor de tipo string
    return string
end note



@enduml