@startuml Diagrama de clases
class Garage {
    - vehiculos: Array<Vehiculo>;
    - reservas: Array<Evento>;
    - mantenimientos: Array<Evento>;
    - ticket: number;

    + comprarCompacto(matricula: string)
    + comprarSUV(matricula: string)
    + comprarSedán(matricula: string)

    + crearReserva()

    + realizarMantenimiento()
    + terminarMantenimiento()

    + limpiarVehiculo()
}

class Cliente {
    + reservar()
    + devolverVehiculo()
}

abstract class Vehiculo {
    - matricula: string
    - necesitaLimpieza: boolean
    
    + abstract obtenerTarifa(dias: number, kilometros: number)
    + abstract obtenerTarifaMantenimiento(dias: number)
}

class Compacto {

}
class Sedán {

}
class SUV {

}

class Evento {
    - cant_dias: number
    - tipoVehiculo: string
    - vehiculo: Vehiculo
    - ticket: number

    + setters_y_getters()

    - calcularCantDias()
}

class Calendario {
    + revisarCalendario()
    + estaDisponibleHoy()
}


' Relaciones

Cliente *-- Garage

Garage *-d- Vehiculo
Garage *-d- Evento

Garage *-r- Calendario

Evento *-r- Vehiculo

Vehiculo <|-- Compacto
Vehiculo <|-- Sedán
Vehiculo <|-- SUV

@enduml